replicaCount: 1

serviceAccount:
  create: true        # let Helm create a ServiceAccount
  automount: true
  annotations: {}
  name: ""            # empty = Helm generates the name

# Force simple name for Deployment + Service
fullnameOverride: ftg-demo-app

image:
  repository: ftg-demo
  tag: "1.0"
  pullPolicy: Never   # use local Minikube image, don't pull from Docker Hub

service:
  type: ClusterIP
  port: 8080

resources: {}

# Postgres settings (for the DB pod we will create)
postgres:
  image: postgres
  tag: "16"
  username: postgres
  password: postgres
  db: demo_db
  port: 5432

ingress:
  enabled: false

  autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80